[project]
name = "dbcli"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "psutil>=7.0.0",
    "pydgraph>=24.1.0",
    "requests>=2.32.3",
]
